version: '3'
services:
    drone-demo:
        build:
            context: ../../
            dockerfile: src/docker/Dockerfile
        privileged: true
        image: drone-demo:1.0
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
